name: R Package Check and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        r-version: ['4.1.0']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
        architecture: 'x64'

    - name: Set up Rtools
      if: runner.os == 'Windows'
      uses: r-lib/actions/setup-rtools@v2

    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install imagemagick@6
        brew install libmagic

    - name: Install R dependencies
      run: |
        install.packages(c("remotes", "rcmdcheck", "devtools"))
        remotes::install_deps(dependencies = TRUE)
      shell: Rscript {0}

    - name: Check package structure
      run: |
        if (file.exists("DESCRIPTION")) cat(readLines("DESCRIPTION"), sep = "\n")
        devtools::check_man()
        devtools::document()
      shell: Rscript {0}

    - name: Remove ltmain.sh if exists
      if: runner.os == 'Windows'
      run: |
        if (file.exists("ltmain.sh")) {
          file.remove("ltmain.sh")
          print("ltmain.sh removed")
        } else {
          print("ltmain.sh not found")
        }
      shell: Rscript {0}

    - name: Check
      env:
        _R_CHECK_CRAN_INCOMING_: false
      run: |
        check_results <- rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        if (length(check_results$errors) > 0 || length(check_results$warnings) > 0) {
          stop("There were errors or warnings in the check")
        }
      shell: Rscript {0}

    - name: Build Package
      run: |
        pkg_file <- devtools::build(binary = (Sys.info()[['sysname']] == "Windows"))
        print(paste("Built package:", pkg_file))
      shell: Rscript {0}

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: msgxtractr_