name: Build Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Display Go version and environment
      run: |
        go version
        go env

    - name: Initialize Go module if not present
      run: |
        if [ ! -f go.mod ]; then
          go mod init github.com/${{ github.repository }}
        fi

    - name: Build
      run: go build -v .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: binary-${{ runner.os }}
        path: |
          ./*
          !.git
          !.github
