name: R Package Check and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        r-version: ['4.1.0']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}

    - name: Install system dependencies
      if: runner.os == 'macOS'
      run: |
        brew install imagemagick@6
        brew install libmagic

    - name: Install R dependencies
      run: |
        install.packages(c("remotes", "rcmdcheck", "devtools"))
        remotes::install_deps(dependencies = TRUE)
      shell: Rscript {0}

    - name: Check package structure
      run: |
        dir
        if (file.exists("DESCRIPTION")) cat(readLines("DESCRIPTION"), sep = "\n")
        devtools::check_man()
        devtools::document()
      shell: Rscript {0}

    - name: Check
      env:
        _R_CHECK_CRAN_INCOMING_: false
      run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
      shell: Rscript {0}

    - name: Show check results
      if: failure()
      run: |
        cat check/00check.log
        cat check/00install.out
      shell: bash

    - name: Build Package
      run: |
        pkg_file <- devtools::build(binary = TRUE)
        print(paste("Built package:", pkg_file))
      shell: Rscript {0}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: R-package-${{ runner.os }}
        path: '*.tar.gz'

    - name: Upload binary artifact (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: R-package-Windows-binary
        path: '*.zip'