name: R Package Check and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        r-version: ['4.1.0']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}

    - name: Install system dependencies
      if: runner.os == 'macOS'
      run: |
        brew install imagemagick@6
        brew install libmagic

    - name: Install R dependencies
      run: |
        install.packages(c("remotes", "rcmdcheck", "devtools"))
        remotes::install_deps(dependencies = TRUE)
      shell: Rscript {0}

    - name: Check package structure
      run: |
        dir
        if (file.exists("DESCRIPTION")) cat(readLines("DESCRIPTION"), sep = "\n")
        devtools::check_man()
        devtools::document()
      shell: Rscript {0}

    - name: Remove ltmain.sh if exists
      if: runner.os == 'Windows'
      run: |
        if (file.exists("ltmain.sh")) {
          file.remove("ltmain.sh")
          print("ltmain.sh removed")
        } else {
          print("ltmain.sh not found")
        }
      shell: Rscript {0}

    - name: Check
      env:
        _R_CHECK_CRAN_INCOMING_: false
      run: |
        check_results <- rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        if (length(check_results$errors) > 0 || length(check_results$warnings) > 0) {
          stop("There were errors or warnings in the check")
        }
      shell: Rscript {0}

    - name: Show check results
      if: failure()
      run: |
        if (file.exists("check/00check.log")) {
          cat("Contents of check/00check.log:\n")
          cat(readLines("check/00check.log"), sep = "\n")
        } else {
          cat("check/00check.log does not exist\n")
          cat("Contents of the current directory:\n")
          print(list.files(recursive = TRUE))
        }
      shell: Rscript {0}

    - name: Build Package
      run: |
        pkg_file <- devtools::build(binary = FALSE)
        print(paste("Built source package:", pkg_file))
        if (Sys.info()['sysname'] == "Windows") {
          bin_file <- devtools::build(binary = TRUE)
          print(paste("Built binary package:", bin_file))
        }
      shell: Rscript {0}

    - name: Upload source package
      uses: actions/upload-artifact@v3
      with:
        name: msgxtractr_${{ runner.os }}_source
        path: '*.tar.gz'

    - name: Upload binary package (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: msgxtractr_Windows_binary
        path: '*.zip'